Repository ktag0629/iNaturalistGo, pull requests merged in 2020-12, with the labels that each got.

#59 Adds iNG Favicon
  Templates/base.html
  static/iNG_favicon.ico
Labels: enhancement

#60 Adds simple tests for Species model
  species/Tests/__init__.py
  species/Tests/test_models.py
  species/tests.py
  users/Tests/test_forms.py
Labels: fragment

#64 Quick fix for species model
  species/migrations/0001_initial.py
Labels: bug

#56 Testing google email
  README.md
  Templates/account/base.html
  Templates/account/base_card.html
  Templates/account/logout.html
  Templates/account/profile.html
  Templates/account/signup.html
  Templates/account/verification_sent.html
  Templates/home/googlec9d04339c6f2434c.html
  Templates/home/home.html
  iNaturalist_447/Tests/test_views.py
  iNaturalist_447/settings.py
  iNaturalist_447/urls.py
  iNaturalist_447/views.py
  media/species_pics/Albert_Einstein_Head.jpg
  requirements.txt
  species/__init__.py
  species/admin.py
  species/apps.py
  species/migrations/0001_initial.py
  species/migrations/__init__.py
  species/models.py
  species/tests.py
  species/views.py
  users/Tests/test_forms.py
  users/Tests/test_views.py
  users/views.py
Labels: enhancement, feature_request
